[meta]
plugin_metadata_version = 0

[plugin]
name = "Patcherex2"
shortname = "patcherex2"
version = "0.0.0"
platforms = ["windows", "linux", "macos"]
min_angr_version = "9.0.0.0"
author = "PurSec Lab"
entrypoints = ["patcherex2_plugin.py"]